
#GRUP ÜYELERİ
#Esra İclal Akyol - B221210032 - 1B
#Sara Mohamed - B221210566 - 1B
#Zeynep Gizem Fırat - B221210074 - 1B
#Sude Dönmez - B221210581 - 1B
#Zeynep Kebapcı - B221210091 - 1A


hepsi: derle calistir

derle:
	gcc -I ./include/ -o ./lib/prompt.o -c ./src/prompt.c
	gcc -I ./include/ -o ./bin/main ./lib/prompt.o ./src/main.c
	

calistir:
	./bin/main
